### ISSUE TITLE
[✨] add mousewheel control to carousel

### ISSUE THREAD

**Issue by patrickkmatias** [qwikifiers/qwik-ui#1025]
### Is your feature request related to a problem?

I'd use qwik-ui's carousel if it had this feature.

### Describe the solution you'd like

like swiperjs does
https://swiperjs.com/demos#mousewheel-control

### Describe alternatives you've considered

I'm sticking with swiperjs today; with a `<script async>` call.

**Comment by thejackshelton** [comment]
Hey Patrick! Looks like I forgot to record my microphone here, but this should be out in the next release of Qwik UI. In the video is how I added the feature in case you would like to make an effort to customize the carousel to more swiper features.

Appreciate the suggestion and merry christmas 🎄 


https://github.com/user-attachments/assets/e423b0d9-fcbe-442d-8c60-9e3a77c7d37a

**Comment by patrickkmatias** [comment]
that's amazing! thanks for the backstage footage also 🤣 

happy christmas 👋🏾
