### ISSUE TITLE
Prefer "class" over "className"

### ISSUE THREAD

**Issue by GregOnNet** [qwikifiers/qwik-ui#108]
## Reproduction

- Starting the website

```
cd packages/website
npm start
```

- The following warning is shown

<img width="522" alt="CleanShot 2023-01-29 at 21 23 20@2x" src="https://user-images.githubusercontent.com/444278/215353933-7e927187-40a4-4088-9b88-bacb2174d02c.png">

## Proposed solution

We might want to replace `className` with `class`.

## Final thoughts

- [x] I am willing preparing a PR for it.

**Comment by shairez** [comment]
thanks @GregOnNet !
go for it! 💪🙏

**Comment by GregOnNet** [comment]
I encounter an error executing `npx nx storybook core` (stated in contribution guideline).
I am using Node 18.

![image](https://user-images.githubusercontent.com/444278/215984836-6fbe885c-b819-4f3b-9bba-45c87d4445ab.png)

So I executed `npx sb@next automigrate` like stated in the error.
This ran the following migrations: 
- 'newFrameworks', 
- 'mainjsFramework', 
- 'addReact'
- 'eslintPlugin'

After the migration storybook does not start.

![image](https://user-images.githubusercontent.com/444278/215985402-6b369756-ca1d-47bd-9323-f023d1e6a2a2.png)

**Comment by GregOnNet** [comment]
So I verified that my change does not break anything by:

```
cd packages/website
npm start # clicking through the components 🤗
```

**Comment by Balastrong** [comment]
I see there are no more `className` props in the project, maybe we can close this issue? cc @gioboa 

Actually, there are some variables here and there called `classNames`, just in case we want to rename those as well, but they shouldn't be a problem so far.

**Comment by gioboa** [comment]
Yes, thanks.
