### ISSUE TITLE
Add dialog component

### ISSUE THREAD

**Issue by GregOnNet** [qwikifiers/qwik-ui#110]
## Motivation

A Dialog is an UX-concept that is often used in projects.
We can provide a Dialog having an API that guides developers through the most common use cases:

- Responsiveness
- Animations/Transitions
- Dragging
- Scrolling long Content

## Inspiration

- [MUI Dialog](https://mui.com/material-ui/api/dialog/)
- [a11y-dialog](https://github.com/KittyGiraudel/a11y-dialog/blob/main/src/a11y-dialog.ts#L1)
- [radix-dialog-primitive](https://www.radix-ui.com/docs/primitives/components/dialog)

## Next Steps

- [x] Study implementation of [a11y-dialog](https://github.com/KittyGiraudel/a11y-dialog/blob/main/src/a11y-dialog.ts#L1)
- [x] Study implementation of [react-a11y-dialog](https://github.com/KittyGiraudel/react-a11y-dialog/blob/main/src/index.tsx)
- [x] Come up with API-Design (hook-API for headless UI vs. component-API)
- [x] Write Tests
- [x] Write documentation
- [ ] Research features of other libraries
  - [x] Sticky Actions Bar for long scrolling content (comes with `Dialog.Actions`)
  - [x] Display Dialog as FullScreen
  - [ ] Allow custom open/close Animations
  - [ ] Allow Dragging Dialog
- [ ] Decide which features make it into the BETA

**Comment by hamatoyogi** [comment]
I'd suggest looking into [Radix Dialog implementation](https://github.com/radix-ui/primitives/blob/main/packages/react/dialog/src/Dialog.tsx).
I remember hearing somewhere that there's a problem with the native HTML Dialog, but can't seem to find the reference.
Also found this while digging:
https://a11y-dialog.netlify.app/

**Comment by GregOnNet** [comment]
@hamatoyogi Thank you very much. I will have a look at it.

**Comment by GregOnNet** [comment]
Here, we have a summary why currently the native `<dialog>`-Element is not a git fit for us: https://a11y-dialog.netlify.app/further-reading/dialog-element

**Comment by GregOnNet** [comment]
Here we have the a11y-Spec for a Dialog: https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/

**Comment by GregOnNet** [comment]
Both Radix and a11y-dialog use a ReadDOM.createPortal to instanciate the Dialg:
- [Radix](https://github.com/radix-ui/primitives/blob/main/packages/react/dialog/src/Dialog.tsx#L121)
- [a11-dialig-react](https://github.com/KittyGiraudel/react-a11y-dialog)

**Comment by GregOnNet** [comment]
Very interesting reads.
I went through various code bases and read different APIs.
To me, [a11y-dialog](https://github.com/KittyGiraudel/a11y-dialog/blob/main/src/a11y-dialog.ts#L1) seems to be a good start.
The design- and a11y-decisions are well documented.

Next up, I study the vanilla JS implementation: https://github.com/KittyGiraudel/a11y-dialog/blob/main/src/a11y-dialog.ts#L1
I also take the React and Solid implementations into account.

I am no React expert, that's why I will start with vanilla JS first to understand the concepts.

**Comment by tleperou** [comment]
> I'd suggest looking into [Radix Dialog implementation](https://github.com/radix-ui/primitives/blob/main/packages/react/dialog/src/Dialog.tsx). I remember hearing somewhere that there's a problem with the native HTML Dialog, but can't seem to find the reference. Also found this while digging: https://a11y-dialog.netlify.app/

If my not mistaken, the API allows app to open modal only on user interaction. Which limit many usages.

**Comment by tleperou** [comment]
I came accros than one recently while investigating on _trap users' focus_

👉  https://micromodal.vercel.app/

if it can still give ideas :)

**Comment by tleperou** [comment]
What's the progress with the modal @GregOnNet , happy to hear from you 🤗 

I'm happy to give some of my time if you see fit.

**Comment by GregOnNet** [comment]
Hi @tleperou,

thanks for the offer.

I did not write any code so far.
Maybe I got a bit lost in researching all the a11y-resources. 

Can I reach you in Discord? I am happy to pair with you. 🧑‍💻🧑‍💻

**Comment by GregOnNet** [comment]
Hi @tleperou,

I checked this repository yesterday.

It is a lightweight & good to understand code base.
However, having a look at the [issues](https://github.com/ghosh/Micromodal/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc), there are a lot of edge cases this solution cannot handle.

That's why I want to drop this idea for now.

**Comment by tleperou** [comment]
🙌

here's my discord ID thameus#6784.

Dialog is a vast topic. As you mentioned, getting in the accessibility details is something!

Do you have come across any considerations about managing/exposing the state?

While working on the combobox, I experimented several options and ended with [that way](https://discord.com/channels/990511757091033108/1040763063533588562/1093365899274235906) of exposing the state.

Indeed, the repo of the modal has some blocking issues. That demonstrates the challenge it can be.

**Comment by thejackshelton** [comment]
@GregOnNet and I added this in beta a couple months back. Closing
