### ISSUE TITLE
Add Checkbox component

### ISSUE THREAD

**Issue by shiroinegai** [qwikifiers/qwik-ui#128]

**Comment by Wimpert** [comment]
I think there is already a checkbox present, it is named toggle (packages/headless/src/components/toggle/toggle.tsx)

````ts
  return (
    <input
      type="checkbox"
      role="switch"
````

What am I missing here?

**Comment by Wimpert** [comment]
Can you explain what the difference in behaviour should be?

**Comment by Wimpert** [comment]
I am happy to take this up.

**Comment by gioboa** [comment]
[This](https://github.com/qwikifiers/qwik-ui/pull/154) PR is already implementing it
