### ISSUE TITLE
Add Select component

### ISSUE THREAD

**Issue by shiroinegai** [qwikifiers/qwik-ui#132]

**Comment by shiroinegai** [comment]
@gioboa Could you assign this one to me? Greg requested for this component for the Rabbit Store tutorial so I'm gonna work on it this week.

**Comment by gioboa** [comment]
Sure 👍

**Comment by tleperou** [comment]
Dropdown as general purpose, or dropdown as input select (multiselect, autocomplete) ?

**Comment by shiroinegai** [comment]
It's a general purpose Dropdown component. Multi-select and auto-complete could be built as extensions to the Select component.

**Comment by tleperou** [comment]
Ok got it;

that one is quiet easy and light

👉  https://floating-ui.com/

**Comment by shiroinegai** [comment]
Qwik UI is actually using that under the hood for several components now!

**Comment by TimKieu** [comment]
I am trying this Select component but how to handle default item and selected item, where is onClick$ or event handler?
pls help, thanks much

**Comment by cwoolum** [comment]
Hi, I see the component is in alpha but this task is in Todo. Are you looking for a contributor to build it out further?

**Comment by nelsonprsousa** [comment]
> Hi, I see the component is in alpha but this task is in Todo. Are you looking for a contributor to build it out further?

I believe @thejackshelton is activelly working on it?

**Comment by thejackshelton** [comment]
> Hi, I see the component is in alpha but this task is in Todo. Are you looking for a contributor to build it out further?

Hey @cwoolum, yeah have been working on it pretty actively since the last sprint. We have a Qwik UI meeting this wednesday where I'll be going over some of the progress. 

Happy to invite to the meeting if you're interested in help pushing that further

**Comment by juanpmarin** [comment]
Hello @thejackshelton, thanks for you great work with this lib!
Is it going to have support for multiple selection?

**Comment by thejackshelton** [comment]
> Hello @thejackshelton, thanks for you great work with this lib! Is it going to have support for multiple selection?

Yep, there's notes in the repo where you can see our current progress 😄

**Comment by nelsonprsousa** [comment]
You can also check the backlog https://github.com/orgs/qwikifiers/projects/1

**Comment by thejackshelton** [comment]
> You can also check the backlog https://github.com/orgs/qwikifiers/projects/1

Ah that might be a bit out of date 😅 . At least I haven't been updating it.

**Comment by thejackshelton** [comment]
I think your best bet is diving into the commits 🤿

**Comment by nelsonprsousa** [comment]
Oh, I still confuse 2024 with 2023 😅

**Comment by cwoolum** [comment]
@thejackshelton, DM'd you on Discord

**Comment by thejackshelton** [comment]
Closing, as this was released in beta last month.

**Comment by juanpmarin** [comment]
@thejackshelton is there a place to follow multi selection support?

**Comment by thejackshelton** [comment]
> @thejackshelton is there a place to follow multi selection support?

@juanpmarin I would say the qwikifiers discord. I'm not necessarily rushing to add it at the moment 😅 , as it's a more advanced use case, will likely be focused on the more common use cases, such as a tooltip, switch, or refactoring current components.

If you'd like to take a crack at it, I'd be happy to walk you through the component.

We also have a contributing guide here:
https://qwikui.com/contributing/
