### ISSUE TITLE
[🐞] Error in local setup

### ISSUE THREAD

**Issue by Adibla** [qwikifiers/qwik-ui#137]
# Which component is affected?
Starters / CLI

## Describe the bug
Using the guide provided in CONTRIBUTING.md, I cannot start storybook on my Macbook. I tried to clear and reinstall all the dependencies but the issue persist.

## Steps to reproduce
git clone git@github.com:qwikifiers/qwik-ui.git
cd ./qwik-ui
npm i
npm run dev --workspace=packages/core (one terminal)
npx nx storybook core (another terminal)

After the latest command i get this error
_Error: Invalid value of @storybook/html in the 'framework' field of Storybook config.
Please run 'npx sb@next automigrate'
See the v7 Migration guide for more information:_ 

## System Info
```
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1000.38 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.1
```

### Additional Information
No response

**Comment by shiroinegai** [comment]
Hey there, CONTRIBUTING.md hasn't been updated yet. In the meantime, use `npx nx start website` in your terminal.

**Comment by Adibla** [comment]
Thank you!
