### ISSUE TITLE
Husky hooks are not executed

### ISSUE THREAD

**Issue by Balastrong** [qwikifiers/qwik-ui#167]
I'm not sure if it's only me, but when I commit (with `npm run commit`, but also with a manual `git commit`) I get this warnings on console and husky hooks are not executed:

```
hint: The '.husky/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
hint: The '.husky/commit-msg' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
```

According to the [answers here](https://stackoverflow.com/questions/8598639/why-is-my-git-pre-commit-hook-not-executable-by-default) a simple `chmod ug+x .husky/*` fixes the issue. I tested it locally and it worked.

Also, after running `chmod` the two husky files are marked as changed so probably creating a PR with that should fix the issue for everyone. I can take care of that :)

**Comment by gioboa** [comment]
will PR #168 commit also resolve husky chmod fix?

**Comment by Balastrong** [comment]
No, but I can add a commit there to fix this

**Comment by gioboa** [comment]
Yes please
