### ISSUE TITLE
Define a type for the Rating icon component

### ISSUE THREAD

**Issue by Balastrong** [qwikifiers/qwik-ui#171]
Eslint is throwing a warning for this `any`.

https://github.com/qwikifiers/qwik-ui/blob/627628e30681842bd1c16109108a71593e82b9a1/packages/headless/src/components/rating/rating.tsx#L15

We should think of a better type to define what can be passed here.

**Comment by gioboa** [comment]
@fabiobiondi I think you can have an idea about this.
