### ISSUE TITLE
Navbar transparent background

### ISSUE THREAD

**Issue by wahyufeb** [qwikifiers/qwik-ui#185]
I got a new bug on the Header component, that does not have a background color.
I think it's a better way to set the background color to the Header.

I think I can solve this issue, just put a background color with --color-bg variable.

<img width="1920" alt="Screen Shot 2023-02-22 at 9 33 25 PM" src="https://user-images.githubusercontent.com/38874570/220653763-f5136431-a366-457b-ad68-244e7467533b.png">

**Comment by gioboa** [comment]
Thanks for your feedback, you're right. Yes, you can open a PR for it.

**Comment by wahyufeb** [comment]
#194
