### ISSUE TITLE
Add Breadcrumb component

### ISSUE THREAD

**Issue by wahyufeb** [qwikifiers/qwik-ui#193]

**Comment by wahyufeb** [comment]
Hi @gioboa, I will work on this.

**Comment by wahyufeb** [comment]
@gioboa Kindly check my PR #212

**Comment by wahyufeb** [comment]
@gioboa I have a question.
Do I have to comment "I have read the CLA Document and I hereby sign the CLA"  in every PR to the main branch?

**Comment by gioboa** [comment]
No, only the first PR. We need to check all-contributors bot maybe there is a bug in the bot code. 😢
