### ISSUE TITLE
Toggle component intialValue

### ISSUE THREAD

**Issue by yishayhaz** [qwikifiers/qwik-ui#209]
TLDR: You cannot initially set the value of `checked` to `true`.

### Code
```js
import { component$, useSignal } from '@builder.io/qwik';
import { Toggle } from '@qwik-ui/theme-daisy';

export default component$(() => {
  const toggleChecked = useSignal(true);
  return (
    <>
      <h2>This is the documentation for the Toggle</h2>
      <Toggle
        checked={toggleChecked.value}
        onClick$={() => {
          toggleChecked.value = !toggleChecked.value;
        }}
      />
    </>
  );
});
```
### Result
![image](https://user-images.githubusercontent.com/50710472/221345840-a868988c-8dbf-4862-ab07-8d684bf11210.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/50710472/221345873-de2160e9-33b8-4976-b34b-ae32128839d7.png)

**Comment by gioboa** [comment]
Is this issue solved?
