### ISSUE TITLE
add Menu component

### ISSUE THREAD

**Issue by wahyufeb** [qwikifiers/qwik-ui#216]

**Comment by wahyufeb** [comment]
Hi @gioboa, I will work on this.

**Comment by gioboa** [comment]
Menu component is already present, am I wrong?

**Comment by wahyufeb** [comment]
The menu show like this 
https://daisyui.com/components/menu/

It's like a Dropdown but has a submenu inside it

**Comment by gioboa** [comment]
So your implementation will be a variant of the menu component, right?

**Comment by gioboa** [comment]
is it a duplicate of [this issue](https://github.com/qwikifiers/qwik-ui/issues/160)?

**Comment by wahyufeb** [comment]
> is it a duplicate of [this issue](https://github.com/qwikifiers/qwik-ui/issues/160)?

I think so, I will work on that😃
