### ISSUE TITLE
add primitive package

### ISSUE THREAD

**Issue by gioboa** [qwikifiers/qwik-ui#223]
Message from @gilf 
---
At this time in the headless package we have the following:
accordion - should be headless but the accordion item should have been divided into item-header and item-content (current version is less reusable)
button - should be a primitive
button-group - should be headless
card - should be headless
collapse - should be an accordion with only one item or the accordion item should have use the collapse component as a child component.
drawer - should be headless
menu - should be headless
pagination - should be headless
popover - should be headless
progress - should be primitive (exposes the input type progress)
radio - should be primitive (exposes the input type radio) also we should have a headless radio-group component
rating - can be headless
select - should be headless
slider - should be headless
spinner - should be primitive
tabs - should be headless
toast - should be primitive
toggle - should be primitive
tooltip - should be headless

There are a few PRs (alert, navigation bar, breadcramb, checkbox and dialog), which also need to be divided to primitives/headless.

**Comment by tleperou** [comment]
Progress or button for instance are existing HTML components, and Qwik provide interfaces already (eg. events).

So, which abstraction primitives shall provid ?
