### ISSUE TITLE
tooltip works only the first time

### ISSUE THREAD

**Issue by gioboa** [qwikifiers/qwik-ui#264]
Here is a video for this issue.
The tooltip works only the first time
https://www.loom.com/share/66f693d2804b4e3d92ef3770cac1c39e

**Comment by pranit-yawalkar** [comment]
Hey, any working on this, if not then I would like to take this.

**Comment by jansedlon** [comment]
A looked at the code and the proposed solution could be to rename the `onAnimationEnd$` to `onTransitionEnd$` and in the `showTooltip` function if could be like this
```ts
if (stateSignal.value === "hidden") {
  stateSignal.value = "unpositioned";
}
``

However it seems like there a event leak somewhere. Not sure if in the code or the Qwik itself, but the more times the tooltip is shown, the more times the `onMouseLeave$` and `onMouseEnter$` events are called

**Comment by gioboa** [comment]
Thanks, you solved the problem, but the first tooltip position seems wrong.
Can you check it please?

<img width="816" alt="Screenshot 2023-04-05 at 11 12 06" src="https://user-images.githubusercontent.com/35845425/230036694-7531e90b-70ef-4788-9b58-a84dac253a76.png">

**Comment by pranit-yawalkar** [comment]
I have pushed the changes, can you please review them?
