### ISSUE TITLE
select doesn't work on mobile and desktop

### ISSUE THREAD

**Issue by tleperou** [qwikifiers/qwik-ui#265]
# Summary

The component Select doesn't work properly on mobile, tested on Opera mini and Chrome. It's realy hard to get it open

**Note**: seems that the floatui struggles to work properly, there's like a layout shifting

![image](https://user-images.githubusercontent.com/8383972/229656354-f4ecb519-d1af-4373-9ea1-385e92e0bcc5.png)

**Comment by a-lukasiewicz** [comment]
Hi, I would like to contribute and resolve this issue. Could it be assigned to me?

**Comment by gioboa** [comment]
@a-lukasiewicz yep, sure. Thanks

**Comment by tleperou** [comment]
@a-lukasiewicz , @gioboa ; could floating-ui struggle to play nicely with qwik ui 🤔 . Looks like there's something to do in order to ensure that floating-ui operates its magic when the chunks (cf. the components) are actually resolved.

**Comment by a-lukasiewicz** [comment]
Oh right, for this pr I made that on simple css styling - relative and absolute position. But there are more cases other than fixing that?

> If the select is at the bottom of the page, the options need to appear on top. 

I will take a look on that floating-ui positioning and try to fix that
