### ISSUE TITLE
do we need an icons folder?

### ISSUE THREAD

**Issue by gioboa** [qwikifiers/qwik-ui#270]
The idea is to collect all the headless and daisy icons in a folder so the components can use them.

**Comment by fmgono** [comment]
i prefer with this one

>   * @qwik-ui/icons/{headless, material, daisy}

**Comment by shairez** [comment]
How about using https://icones.js.org/ ?

**Comment by fmgono** [comment]
Wow, cool! that's a lot of icons, and also Qwik is already integrated (even just the Qwik component with svg in it).

But I wonder, with Icones, do we need to download all of the icon sets or just cherry-pick one or two icon sets?
