### ISSUE TITLE
feat(password): create password component

### ISSUE THREAD

**Issue by PatrykGodlewski** [qwikifiers/qwik-ui#279]
An input field password, with a confirmation input

details: the password input is part of the [#266](https://github.com/qwikifiers/qwik-ui/issues/266)

**Comment by PatrykGodlewski** [comment]
I would like to contribute and create that component. Could it be assigned to me? @gioboa

**Comment by tleperou** [comment]
## password [#](https://github.com/qwikifiers/qwik-ui/issues/266#password)
An input field password, with a confirmation input

### Expected
Additionally to the WIA/ARIA specifications,

* regex strength based validation
* visible / not visible string
* confirmation input

----

Including dependencies shall be questioned, meanwhile reinventing the wheel shall be avoid. So I open the topic with this password checker that I recently got into: [checkpass](https://www.npmjs.com/package/checkpass). 

The idea is to expose a light interface to Qwik-ui's users while providing the high level of accessibility standards (and arguably, high level of good practices). I got thought some documentation, including those one (share your if any too)

- https://incl.ca/show-hide-password-accessibility-and-password-hints-tutorial/
- https://design-system.service.gov.uk/patterns/passwords/
- https://hds.hel.fi/components/password-input

The anatomy of the headless shall be composable, HTML valid ([w3c](validator.w3.org)) and Axe valid (using the Axe Chrome extension) ✌️.

I'm happy to get involved where you see fit.

🙏

**Comment by tleperou** [comment]
Awesome @PatrykGodlewski 👏  I gave a look already and will be happy to contribute too

**Comment by tleperou** [comment]
🙌 

@PatrykGodlewski , I (re)implemented the component you made using two patterns:

* composable element
* hook

The contributor team is still discussing about the later ([Discord thread](https://discord.com/channels/990511757091033108/1103862260436307978/1103862260436307978)).

For using the hook, I had to re-manipulate the integrality of your implementation.

Also, I upgraded `checkpass` to the version 3.0.0 and asked the author to expose the `Constraints` type  – which he did very quickly.

It works like a charm.

Could we add a password meter – [like here](https://www.w3.org/WAI/tutorials/forms/examples/password/). What do you think; could you give a hand 💪  ?

**Comment by tleperou** [comment]
Using the two patterns, we end with such integration:

```ts
export default component$(() => {
    const input = useInputPassword();

    return (
        <InputPassword.Root {...input}>
          <InputPassword.Input />
          <InputPassword.Toggler>
            <InputPassword.Icon />
          </InputPassword.Toggler>
        </InputPassword.Root>
    )
});
```

where `input` provides the state of the component:

```tsx
<ul>
  <li>Password: {input.value.value}</li>
  <li>Visible: {input.visible.value ? 'yes' : 'no'}</li>
  <li>
    Errors:
    <ul>
      {input.errors.value.map((error, i) => (
        <li key={i}>{error.message}</li>
      ))}
    </ul>
  </li>
</ul>
```

**Comment by PatrykGodlewski** [comment]
Awesome @tleperou! Previously, I attempted using an existing pattern in the project, but I was unaware of the Discord thread. However, I do have some questions regarding your implementation. Would it be possible to include a toggler for the confirmInput as well, since we already have one for the main input? By doing so, the implementation would look like this.
```TSX
export default component$(() => {
    const input = useInputPassword();

    return (
        <InputPassword.Root {...input}>
          <InputPassword.Input>
            <InputPassword.Toggler>
              <InputPassword.Icon />
            </InputPassword.Toggler>
          </InputPassword.Input>
          <div>confirm</div>
          <InputPassword.InputConfirm>
            <InputPassword.Toggler>
              <InputPassword.Icon />
            </InputPassword.Toggler>
          </InputPassword.InputConfirm>
        </InputPassword.Root>
    )
});
```
Also, I think adding a password meter would be a great idea. Thank you for suggesting it! I'll make sure to work on that as soon as possible.

**Comment by tleperou** [comment]
🙌

do you think the visibility state of the confirm shall be exposed ?

**Comment by PatrykGodlewski** [comment]
In my view, there's not really a major downside to this solution. We're making it optional, so anyone who doesn't like it can just choose not to use it. However, I'm open to feedback, and if there's something I've overlooked, please don't hesitate to point it out.

**Comment by PatrykGodlewski** [comment]
Should the functionality of the password meter be based on Checkpass or perhaps we should consider using a tool like [zxcvbn](https://www.npmjs.com/package/zxcvbn?activeTab=readme)?
