### ISSUE TITLE
feat(badge) Make the badge more accessible

### ISSUE THREAD

**Issue by tleperou** [qwikifiers/qwik-ui#292]
# Summary

Badges shall use by default status role and content flow DOM elements.

Such implementation helps follow the WAI ARIA and HTML practices:

```tsx
<span class="..." role="status"><Slot /></span>
```

# Concerns

* we could let integrators customise the role

**Comment by fmgono** [comment]
So, this is just replacing the `div` element with `span` and adding the `role` attribute?
Appreciate it if you can let me take this one then.

*This will be my first contribution to the Qwik open-source project

**Comment by tleperou** [comment]
That's correct @fmgono 👌

**Comment by fmgono** [comment]
working on it!
