### ISSUE TITLE
Finalize Tooltip component

### ISSUE THREAD

**Issue by shairez** [qwikifiers/qwik-ui#310]
- [x] Has docs
- [ ] Covered by component tests
- [x] Passes a11y tests
- [x] Fully featured

**Comment by osdiab** [comment]
Looking at the tooltip component, it looks like it demands that the tooltip contents have to be a string and cannot be other content (e.g. what would I do if I, say, wanted to put an icon inside the tooltip?)

Personally I think it would make sense to allow the rendered content to be provided with (or overridden by) a `Slot` to achieve similar flexibility as mature libraries like Radix, though what do you think?

**Comment by osdiab** [comment]
Sounds like this is basically outdated and to be superseded by a rewrite to make the Tooltip be implemented with Popovers.

https://github.com/qwikifiers/qwik-ui/issues/714#issuecomment-2070910601
https://github.com/qwikifiers/qwik-ui/issues/713#issuecomment-2070912537
https://github.com/qwikifiers/qwik-ui/issues/714#issuecomment-2070985884

@thejackshelton should we use this as the issue to track reimplementation of the tooltip or should it be a separate new issue?

**Comment by thejackshelton** [comment]
sure!
