### ISSUE TITLE
Insufficient Contrast in PreviewCodeExample TabPanels in Light Mode

### ISSUE THREAD

**Issue by Knat-Dev** [qwikifiers/qwik-ui#335]
# Description
The `PreviewCodeExample` component exhibits an issue with the contrast of the `TabPanel` elements specifically in light mode. The current `bg-slate-700` background color does not provide sufficient contrast against the text content, resulting in reduced readability.

# Screenshot
![image](https://github.com/qwikifiers/qwik-ui/assets/42738259/5d0ac072-bf17-4175-9e1e-833a800107e2)

# Proposed Solution
I have a fix ready for the contrast issue in the PreviewCodeExample component that adjusts the background color of the TabPanel in light mode. If the maintainers agree that this issue should be addressed, I can submit a pull request with the proposed changes for PreviewCodeExample. Additionally, I am committed to addressing the remaining dark mode issues in the future as my schedule permits, ensuring a consistent and accessible experience throughout the application.

**Comment by shairez** [comment]
That's awesome @Knat-Dev ! Thanks for this!

Will merge any PR that improves a11y (any any improvement to the website in general)

Thanks 🙏

**Comment by Knat-Dev** [comment]
PR ready for review. [Link](https://github.com/qwikifiers/qwik-ui/pull/341)

**Comment by shairez** [comment]
Great job! thanks @Knat-Dev ! 🙏
