### ISSUE TITLE
feat(credit card): create credit card component

### ISSUE THREAD

**Issue by balaji-sivasakthi** [qwikifiers/qwik-ui#339]
# Summary
A (up to) three fields to let users give their payment card info
# Expected
- inputs number, ccv and date
- format number (mask)
- basic validation
- regex based card type identification
# Not expected
- state management
- interface with payment systems

**details**: the credit card input is part of the #266

**Comment by balaji-sivasakthi** [comment]
@gioboa

**Comment by gioboa** [comment]
@thejackshelton pls have a look at this PR.
