### ISSUE TITLE
Feature request: Adding accessibility to the library

### ISSUE THREAD

**Issue by Zankel-Engineering** [qwikifiers/qwik-ui#359]
Removed

**Comment by Zankel-Engineering** [comment]
Yayaya I think it is not fair to use the open source stuff the whole time and to not contribute. I will add the accessibility stuff myself and open a pull request. Never understood how you guys can put so much time into open source projects, while not being paid for it. Doesn't mean that I don't have much respect for it, I have. But yeah I feel like I should fix at least my stuff myself, when I use the things you provide to my own advantage and not for some company that I am consulting or freelancing in.

**Comment by gioboa** [comment]
Thanks for your report and for your help

**Comment by Zankel-Engineering** [comment]
Hi I opened a pull-request: https://github.com/qwikifiers/qwik-ui/pull/363. Don't want to write tests here. It is nonsense for that cheap feature. But I like that you use cypress component tests. I think unit tests or mostly nonsense in general. I like to run E2E-tests against a tape server in the local frontend-setup for the customer applications and yeah cypress component tests are also cool. Unit tests only make sense at certain places imo. I hate all that mocking and mainting all the mocks then.

Hope you are happy with the first draft. We could type it better to omit or pick only certain attibutes and extend it to the other components as well, if you like the approach.

Nice weekend for you guys.

**Comment by Zankel-Engineering** [comment]
But now as I was walking down the stairs. I think that memozation is not a good idea. I will think about it how we can make it more intelligent. It will just use memory when the properties change often. Was just thinging about the small use case.

**Comment by Zankel-Engineering** [comment]
He spent the whole day on the feature. I am not happy with it. Mostly you forget the stuff, when you don't use a framework or library for some time. Had to look some stuff up again. Let me know if that solution fits you guys now.

**Comment by Zankel-Engineering** [comment]
Hi I was reflecting a bit and what I said about open source development. I think it can be interpreted as a little bit arrogant. That was not my intend. Open source is important and I am happy that you guys are doing it. I was just asking myself where you find the time, because I really have to hustle hard to cover my costs at the moment. I don't know about the rest of the world but here in Germany at least the market as a software freelancer has changed a bit. So don't take it wrong what I wrote above.

I linked the fixes into my personal project, so for that it is not needed anymore. Just let me know if you are happy with the changes so that I can remove the fork from my account or adjust it if you want some changes.

**Comment by shairez** [comment]
Thanks @Zankel-Engineering for your contibution and thoughtful discussion

I've reviewed your PR and wrote my reply there
Please let me know there if you need any assitance
Thanks! 🙏

**Comment by Zankel-Engineering** [comment]
Hi I pushed the requested changes.

**Comment by shairez** [comment]
Thanks @Zankel-Engineering 
I'll review it on the PR itself
