### ISSUE TITLE
Separator component 

### ISSUE THREAD

**Issue by NexonTreeHouse** [qwikifiers/qwik-ui#397]
Hi, 
I would like to create a separator component as seen [here](https://www.radix-ui.com/primitives/docs/components/separator) in radix-ui.

Im not sure if this would be part of the headless kit or the primitives.

:)

**Comment by thejackshelton** [comment]
Hey @NexonTreeHouse! 

First off, thanks for stopping by and making an issue! I believe it would be part of the headless kit. 

We're currently working on the more common use case components, such as the combobox and dialog, and we'd love your help there, but if you want to make a separator component I don't see why not! As long as it is accessible, it seems like a simple component, but it may be worth looking into how Radix did it in-depth to make sure it's an accessible API

@shairez would love to hear your thoughts here.

**Comment by NexonTreeHouse** [comment]
Thanks for the response! 

> We're currently working on the more common use case components, such as the combobox and dialog, and we'd love your help there

I would be happy to help, however, I have never really done any open source contributing so, I might do the separator as a good first issue. Then see how I go with some of the less simple components.
