### ISSUE TITLE
Selected tab isn't working, shorthand tabs aren't either

### ISSUE THREAD

**Issue by janat08** [qwikifiers/qwik-ui#409]
The longform:
      <Tabs >
        <TabList seletedIndex={1}>
          <Tab >Tab 1</Tab>
          <Tab>Tab 2</Tab>
          <Tab>Tab 3</Tab>
        </TabList>

        <TabPanel>Content 1</TabPanel>
        <TabPanel>Content 2</TabPanel>
        <TabPanel>Content 3</TabPanel>
      </Tabs>

Causes a typeerror, with not tab shown as selected. The shortform is outright broken as used in docs.

**Comment by thejackshelton** [comment]
Hey @janat08! Thanks for creating an issue. Could you make a reproduction of this behavior with something like stackblitz please? Along with any error messages?

What I see above is what looks to be like half of the tabs short form API.
