### ISSUE TITLE
Rating component

### ISSUE THREAD

**Issue by chuikoffru** [qwikifiers/qwik-ui#413]
I'd like to contribute in this repo, and create rating component like this https://daisyui.com/components/rating
I used that rating in qwik project, but faced with troubles, and I'd like to fix it, to use in my project.

**Comment by thejackshelton** [comment]
Hey @chuikoffru! This sounds like a good use case for our fluffy kit, which is our styled version. 

@shairez thoughts?

**Comment by chuikoffru** [comment]
I'm sorry, I didn't know that Rating component for qwik already exists. 
I found a needed for me solution, thanks. 

> qwik-ui/packages/kit-headless/src/components/rating
