### ISSUE TITLE
BUG: in docs, showing "QWIK WARN Serializing dirty task. Looks like an internal error."

### ISSUE THREAD

**Issue by shairez** [qwikifiers/qwik-ui#422]
So ever since we've changed the headless tabs code we've been getting these error messages:

`QWIK WARN Serializing dirty task. Looks like an internal error. `

This is coming from the "pause" process in Qwik.

I've added [a feature to Qwik](https://github.com/BuilderIO/qwik/pull/5182) so we'll know why this is happenning.

In the meantime, I've debugged it and figure out that when I comment out [this function call](https://github.com/qwikifiers/qwik-ui/blob/main/packages/kit-headless/src/components/tabs/tabs.tsx#L258)... the errors goes away

@wmertens have any idea why this call would leave the task in a dirty state?
(my assumption is that it's because we're doing things syncronously, where they are in fact suppose to be async, like signal changing, but I'm not sure)

**Comment by maiieul** [comment]
Closing as this was fixed in qwik 1.7.0 iirc.
