### ISSUE TITLE
📜 EPIC: Qwik UI Styled components

### ISSUE THREAD

**Issue by shairez** [qwikifiers/qwik-ui#426]
Tasks to do complete:

- [x] #430
- [x] #428
- [x] #427
- [x] #451
- [x] #456
- [x] #454
- [x] #447
- [x] #429
- [x] #434
- [x] #432
- [x] #435
- [x] #431
- [x] #433
- [x] #436
- [x] #437
- [ ] #438
- [ ] #439
- [x] #440
- [x] #441

**Comment by maiieul** [comment]
Closing as I think we can simply add the styled tooltip and toggle when the headless ones will be ready
