### ISSUE TITLE
Create styled Dialog

### ISSUE THREAD

**Issue by shairez** [qwikifiers/qwik-ui#440]

**Comment by black-arm** [comment]
can I have this task?

**Comment by gioboa** [comment]
Yep, go for it. Thanks for your help @black-arm

**Comment by maiieul** [comment]
Hey @black-arm! PRs are more than welcome! Although we already have the styled Modal https://qwikui.com/docs/styled/modal/


We need to make a better job at communicating our Roadmap, what's done, and what needs to be done.

Here's the current sprint: https://github.com/qwikifiers/qwik-ui/issues/684

So I'm closing this for now but feel free to re-open an issue if you see shortcomings on the styled Modal. Thank you and you're very much welcome to join us on Discord to chat 🕺
