### ISSUE TITLE
Tabs component does not render when put in a reusable component in user land

### ISSUE THREAD

**Issue by thejackshelton** [qwikifiers/qwik-ui#466]
The <Tabs /> root component is an inline component. What it does is walk the JSX so that we can get the indexes at pre-render time.

Unfortunately, there is an issue where if someone creates their own consumable components for the tabs, then it will bug out and nothing will render. We are given the default block of the switch case when walking the JSX

I have a minimal reproduction here:
https://github.com/thejackshelton/tabs-inline-comp-issue

```tsx
unhandled component function QwikComponent(props, key, flags) {
        assertQrl(componentQrl);
        assertNumber(flags, 'The Qwik Component was not invoked correctly');
        const hash = qTest ? 'sX' : componentQrl.$hash$.slice(0, 4);
        const finalKey = hash + ':' + (key ? key : '');
        return _jsxC(Virtual, {
            [OnRenderProp]: componentQrl,
            [QSlot]: props[QSlot],
            [_IMMUTABLE]: props[_IMMUTABLE],
            children: props.children,
            props,
        }, flags, finalKey);
    } given to Tabs
```

Take note of user-tabs.tsx
```tsx
import { Slot, component$ } from "@builder.io/qwik";
import { Tabs, TabList, TabPanel, Tab } from "@qwik-ui/headless";

export const MyTabs = (props: any) => {
  return <Tabs>{props.children}</Tabs>;
};

export const MyTabList = component$(() => {
  return (
    <TabList>
      <Slot />
    </TabList>
  );
});

export const MyTabPanel = component$(() => {
  return (
    <TabPanel>
      <Slot />
    </TabPanel>
  );
});

export const MyTab = component$(() => {
  return (
    <Tab>
      <Slot />
    </Tab>
  );
});
```

And then where we consume it in **index.tsx**
```tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { MyTabs, MyTabList, MyTabPanel, MyTab } from "../components/user-tabs";

export const UserTabs = component$(() => {
  return (
    <MyTabs>
      <MyTabList style={{ background: "red" }}>
        <MyTab>Tab 1</MyTab>
        <MyTab>Tab 2</MyTab>
        <MyTab>Tab 3</MyTab>
      </MyTabList>
      <MyTabPanel>Panel 1</MyTabPanel>
      <MyTabPanel>Panel 2</MyTabPanel>
      <MyTabPanel>Panel 3</MyTabPanel>
    </MyTabs>
  );
});

export default component$(() => {
  return (
    <>
      <h1>Hi 👋</h1>
      <p>
        Can't wait to see what you build with qwik!
        <br />
        Happy coding.
      </p>
      <UserTabs />
    </>
  );
});

export const head: DocumentHead = {
  title: "Welcome to Qwik",
  meta: [
    {
      name: "description",
      content: "Qwik site description",
    },
  ],
};
```

**Comment by wmertens** [comment]
The reason is that Tabs checks the components it gets, it doesn't know what MyTablist is. The MyTabs wrapper needs to change those.

**Comment by thejackshelton** [comment]
> The reason is that Tabs checks the components it gets, it doesn't know what MyTablist is. The MyTabs wrapper needs to change those.

I'm not sure what you mean. How else would we change it?

As in you mean it all needs to be in one component? Instead of their own separate components?

**Comment by maiieul** [comment]
Think it's the problem with the switch.

**Comment by maiieul** [comment]
Trying to debug another error, I copied the Tabs code in qwikcn to consume it directly and I get the following error:

> unhandled component function e(l,s,o){const r=t.$hash$.slice(0,4);return d(Hn,{"q:renderFn":t,[$e]:l[$e],[F]:l[F],children:l.children,props:l},o,r+":"+(s||""))}

Not sure if that's going to help though :sweat_smile:

**Comment by wmertens** [comment]
Another approach could be to pass the components to Tabs so it knows about them. You'd make your own Tabs wrapper like

```tsx
const MyTabs = (props) => <Tabs {...props} TabComponent={MyTab} TabListComponent={MyTabList} />
```
