### ISSUE TITLE
Accordion does not re-adjust AccordionContent height on window width change

### ISSUE THREAD

**Issue by maiieul** [qwikifiers/qwik-ui#467]
Not urgent because it only happens when manually resizing the window. But still good to have imo.

When the width of the window changes, which to my understanding can be done manually on desktop or can happen when changing orientation on mobile, the AccordionContent height does not re-adjust itself for the content inside to fit in.

Potentially useful input from @thejackshelton :

> [...] we're currently calculating the children content for the height animation. My understanding is we can't calculate the content component height because it starts at 0px and so the method defaults to null or 0px
> seems like some refactoring needs to be done there
> but if you're talking about calculating height based on resizing the window, yes we'd want an onresize event.

Radix/ui's Accordion does it automatically. Could be worth looking into their code or their Accordion behavior to see what needs to be done.

**Comment by cwoolum** [comment]
@maiieul , I believe you fixed this in https://github.com/qwikifiers/qwik-ui/pull/605 with `useOnWindow('resize', context.getContentDimensions$);`. Can you confirm if this is still a problem for you?

**Comment by maiieul** [comment]
Yup, seems to be working now thanks 👍

**Comment by shairez** [comment]
@maiieul said to reopen it 😅

**Comment by maiieul** [comment]
Ah no this is fixed i think sorry
