### ISSUE TITLE
Make CONTRUBUTING.md easier to "copy and paste" 

### ISSUE THREAD

**Issue by TheMcnafaha** [qwikifiers/qwik-ui#476]
Currently, this file has a mix of bullet points containing code to paste into the CLI and shell snippets. Below I attached parts of Step 4 and  Step 10 as they are now (355a5fb) to show what I mean:

### ▶ 4. Run the library

- From the root of the project run `pnpm install`.

### ▶ 10. After your PR is merged - delete your branches

After your pull request is merged, you can safely delete your branch and pull the changes from the main (upstream) repository:

- Delete the remote branch on GitHub either through the GitHub web UI or your local shell as follows:

  ```shell
  git push origin --delete my-fix-branch
  ```

I think the whole file should change to use shell snippets like Step 10 does. It's just easier to click on the copy button than having to highlight the text and then copying it.  

I'd love to get this done if other people agree with me.

**Comment by maiieul** [comment]
I think you can always submit a PR for that kind of change and explain your reasoning in your PR. It should be accepted!

**Comment by TheMcnafaha** [comment]
Got it, will get that done.

**Comment by gioboa** [comment]
Closed by #478
