### ISSUE TITLE
Add "merge" to class / className

### ISSUE THREAD

**Issue by shairez** [qwikifiers/qwik-ui#54]
Currently the `...props` is overriding the inner `class` of the component

for example: 

```
<Alert class="alert-success">Message</Alert>

```
Will not render correctly because it'll replace the built in `alert` class inside the component 

We need to merge them so both `alert` and `alert-success` will be part of the inner component's css class

**Comment by gilf** [comment]
This is a change that need to be done in all the components. I suggest to add a library such as classnames (https://www.npmjs.com/package/classnames) to manage that more easily for us and to generate the appropriate class name according to the props and inner component state.

**Comment by shairez** [comment]
good idea
