### ISSUE TITLE
DOCS - Issue with images in preview

### ISSUE THREAD

**Issue by thejackshelton** [qwikifiers/qwik-ui#549]
In dev mode the images work great, but in the preview build we get a rollup error.

This is outside of the problem where images to do not work with Qwik's `?jsx` optimizations from vite 5. (CJS deprecated)

```tsx
Rollup failed to resolve import "/images/qwik-ui-fluffy-creature-screen.webp" from "/home/jackshelton/dev/open-source/qwik-ui/apps/website/src/routes/docs/fluffy/(getting-started)/introduction/index.mdx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

To reproduce:
- grab latest changes from main
- `pnpm i` and `nx preview-cloudflare website`

should get the error.

The preview build also hangs right now, and I believe it's this problem that is causing it.

**Comment by shairez** [comment]
can it be a bug we need to fix in Qwik @thejackshelton ?

**Comment by gioboa** [comment]
This one could be related https://github.com/BuilderIO/qwik/pull/5525 🤔

**Comment by thejackshelton** [comment]
Fixed
