### ISSUE TITLE
Module '"@qwik-ui/headless"' has no exported member 'ComboboxLabel'.ts(2305)

### ISSUE THREAD

**Issue by thejackshelton** [qwikifiers/qwik-ui#594]
Multiple components from Qwik UI headless either are not found, or their type declarations are not found.

It looks to me like it can't find the component perhaps?

reproduction in `combobox.tsx`
https://stackblitz.com/edit/qwik-starter-u9h17r?file=src%2Fcomponents%2Fcombobox%2Fcombobox.tsx

related: #595

**Comment by maiieul** [comment]
Yes I'm having this as well when copying the dist of the latest qwik-ui headless version and pasting it in node_modules/@qwik-ui/headless

<img width="850" alt="image" src="https://github.com/qwikifiers/qwik-ui/assets/45822175/0d554cea-c1a4-4248-8c4d-f48c1a150681">

**Comment by maiieul** [comment]
So it means that the problem is happening in the headless kit.


Underlying typescript issue: https://github.com/microsoft/TypeScript/issues/5711

**Comment by maiieul** [comment]
Ok I found where the bug started to happen: 11361fbf Merge pull request #584 from maiieul/up-1.3.2

You can `git checkout 11361fbf` from main, `pnpm i` and `pnpm build.headless` and you will see these warning messages:

> [
  `Exported variable 'AccordionContent' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'AccordionContent' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Badge' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Badge' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Breadcrumb' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Breadcrumb' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Card' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Card' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'CardBody' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'CardBody' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'CardActions' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'CardActions' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Items' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Items' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Controls' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Controls' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Label' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Label' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'ComboboxLabel' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'ComboboxLabel' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'ComboboxControl' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'ComboboxControl' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'ComboboxTrigger' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'ComboboxTrigger' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'ComboboxPopover' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'ComboboxPopover' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'ModalContent' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'ModalContent' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'ModalFooter' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'ModalFooter' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'ModalHeader' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'ModalHeader' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Label' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Label' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Hint' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'Hint' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'NavigationBar' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'NavigationBar' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'NativeSelect' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'NativeSelect' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'SelectTrigger' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'SelectTrigger' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'SelectMarker' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'SelectMarker' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'SelectListBox' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'SelectListBox' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'SelectLabel' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'SelectLabel' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'TabList' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'TabList' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'TabsImpl' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'TabsImpl' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'TabsImpl' has or is using name 'HTMLElementAttrs' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`,
  `Exported variable 'TabsImpl' has or is using name 'QwikAttributes' from external module "/home/runner/work/qwik-ui/qwik-ui/node_modules/.pnpm/@builder.io+qwik@1.3.2_@types+node@20.10.6_sass@1.69.7_undici@5.28.2/node_modules/@builder.io/qwik/core" but cannot be named.`
]

But if you go to previous commit with `git checkout HEAD~1`, install and build again, you won't see the error.


I believe it's more likely to be a bug in the type changes introduced in Qwik than the few type changes I made in Qwik-ui.

**Comment by wmertens** [comment]
@maiieul can you try with the `dev` release? `@builder.io/qwik@dev` etc

**Comment by maiieul** [comment]
@wmertens I deleted node modules and pnpm lock file, then installed with `@builder.io/qwik@dev`, but this doesn't solve the issue and adds another issue on top for Qwik-City Form components:

> packages/kit-headless/src/components/action-button/action-button.tsx:17:6 - error TS2786: 'Form' cannot be used as a JSX component.
  Its type '<O, I>({ action, spaReset, reloadDocument, onSubmit$, ...rest }: FormProps<O, I>, key: string | null) => Element' is not a valid JSX element type.
    Type '<O, I>({ action, spaReset, reloadDocument, onSubmit$, ...rest }: FormProps<O, I>, key: string | null) => Element' is not assignable to type '(props: Record<any, any>, key: string | null, flags: number, dev?: DevJSX | undefined) => JSXOutput | Promise<JSXOutput>'.
      Type 'Element' is not assignable to type 'JSXOutput | Promise<JSXOutput>'.
        Type 'JSXNode<unknown>' is not assignable to type 'JSXNode<string | ((props: Record<any, any>, key: string | null, flags: number, dev?: DevJSX | undefined) => JSXOutput | Promise<JSXOutput>)>'.
          Types of property 'type' are incompatible.
            Type 'unknown' is not assignable to type 'string | ((props: Record<any, any>, key: string | null, flags: number, dev?: DevJSX | undefined) => JSXOutput | Promise<JSXOutput>)'.

**Comment by wmertens** [comment]
@maiieul did you replace all qwik packages with the dev version?

**Comment by maiieul** [comment]
@wmertens yes

**Comment by thejackshelton** [comment]
@wmertens @maiieul looks like consumers still can't use the library. I guess this is an issue with 1.3.2?

**Comment by maiieul** [comment]
We need to upgrade to 1.3.4 and release a new version!
