### ISSUE TITLE
@qwik-ui/headless - types typo

### ISSUE THREAD

**Issue by flamrdevs** [qwikifiers/qwik-ui#630]
npm

![image](https://github.com/qwikifiers/qwik-ui/assets/71713464/b8419493-ba06-4aaf-a815-c3c21ce54f2d)

![image](https://github.com/qwikifiers/qwik-ui/assets/71713464/9571a1f5-f17e-41dc-b9f4-c5264e8c33fc)

possible solution

```json
{
  "types": "./index.d.ts",
  "type": "module",
  "exports": {
    ".": {
      "types": "./index.d.ts",
      "import": "./index.qwik.mjs",
      "require": "./index.qwik.cjs"
    }
  }
}
```

**Comment by thejackshelton** [comment]
@flamrdevs thank you for pointing this out! I specifically get this issue in Astro, and it seems to be working as intended in both an Astro and Qwik City project after the changes, will make a PR 👍
