### ISSUE TITLE
Copy action is not working for styled page

### ISSUE THREAD

**Issue by harshmangalam** [qwikifiers/qwik-ui#660]
Copy button is not copying the commands in styled page section.

**Comment by harshmangalam** [comment]
After some debugging found  that `__rawString__` is receiving undefined in `mdx-component` hence the copy button action is copying empty value.

**Comment by thejackshelton** [comment]
Hey @harshmangalam! Yeah from the looks of it this is only happening to code snippets that are not inside of a tabs component.

Likely the rehype code whenever the triple tilde code block is used in mdx. (```tsx, ```css, etc.)

Want to take a stab at it? @maiieul might have some insight on where to go from here

**Comment by maiieul** [comment]
Hey thanks for reporthing the issue @harshmangalam! I'll have a look at it with @b4thestorm :)
