### ISSUE TITLE
Dark mode styling broke on the docs site for combobox

### ISSUE THREAD

**Issue by cwoolum** [qwikifiers/qwik-ui#661]
On the docs site, when using a dark theme on the system, the ComboBox options are dark even though the page theme is light

![image](https://github.com/qwikifiers/qwik-ui/assets/942415/29874c3f-3118-49a7-9330-18b17095161f)

In dark mode, the text color is still set to light mode which makes the test unreadable. 

![image](https://github.com/qwikifiers/qwik-ui/assets/942415/89a9a4de-e37b-46de-81da-de572618a538)

@shairez , we may be able to use our accessibility tests ([color-contrast](https://dequeuniversity.com/rules/axe/4.4/color-contrast)) to ensure that theming issues like this don't occur.

I'll work on a fix for this

**Comment by shairez** [comment]
Great idea!! Thanks a lot! 🙏
