### ISSUE TITLE
Combobox not rendering selected item correctly

### ISSUE THREAD

**Issue by xav-ie** [qwikifiers/qwik-ui#670]
1. select item in list
2. clear selection
3. notice that where you selected item in list is now being reported as selected

The selected item seems to be be index based, but does not take into account the list indices changing on combo text input. 

Example:
1. Input "J"
combo input: "J"
list:
- joe
- joseph
- joseppi

2. you select "joseppi"
combo input: "J"
list:
- joe
- joseph
- joseppi <- selected

3. you then combo input text.
combo input: ""
list:
- alice
- bob
- cool kid <- selected
- joe
- joseph
- joseppi 

The "selected" item is not accurate here. It should probably always show the selected item. I think it should probably be alphabetized into the results list.

**Comment by thejackshelton** [comment]
Oh wow, that is definitely a bug haha. Thanks for bringing this to our attention, will try to reproduce

**Comment by maiieul** [comment]
Still an issue @thejackshelton ?

**Comment by thejackshelton** [comment]
fixed in qwik ui 0.5
