### ISSUE TITLE
Add date/time picker component

### ISSUE THREAD

**Issue by iancharlesdouglas** [qwikifiers/qwik-ui#673]
Add a date/time picker (popup calendar) based on Flatpickr, like in the Carbon Design System.

**Comment by maiieul** [comment]
@diecodev has started working on a date picker? Will it also be a time picker @diecodev? Could you add some info in here pls 🙏

**Comment by maiieul** [comment]
Actually let's continue the conversation in https://github.com/qwikifiers/qwik-ui/issues/123.
