### ISSUE TITLE
dialog:modal has default max-width and max-height 38px smaller than the page

### ISSUE THREAD

**Issue by maiieul** [qwikifiers/qwik-ui#674]
This makes creating a side sheet that takes full-width and full-height non-intuitive, both with the headless and styled Modal component.

After discussing this with @thejackshelton, we see two ways to solve this:

1) unset the browser default styles (like tailwind does for a lot of HTML tags) with something like `max-width: unset` anvd `max-height: unset` in the headless modal component itself. This might be easier said than done.

2) override the styles in global.css as part of the styled kit using something like `max-width: 100svh` `max-height: 100svh`.

**Comment by thejackshelton** [comment]
Merged to main. Closing
