### ISSUE TITLE
class-variance-authority is not installed by the CLI

### ISSUE THREAD

**Issue by Balastrong** [qwikifiers/qwik-ui#698]
### As Is
Not a blocker but maybe it's worth mentioning, on a fresh project after installing qwik-ui and the button component, I noticed `class-variance-authority` was not installed.

### Repro Steps
1. Create a new qwik project
2. Install qwik-ui `pnpm dlx qwik-ui init`
3. Install the button component `pnpm qwik-ui add button`

### To Be
Since the button component has an import from `class-variance-authority` I was expecting the cli to automatically add it on package.json, either on the lib install or when adding a component (e.g. button) that uses it.

**Comment by LazyClicks** [comment]
+1

**Comment by shairez** [comment]
thanks @Balastrong !

@maiieul did you add it as a dependency to the styled component? or should it be installed separately?

**Comment by maiieul** [comment]
@shairez It should be installed with the cli. Do we simply need to add it to dependencies on the styled kit?

**Comment by brandiqa** [comment]
I would also like to add that `@qwikest/icons` and `tailwindcss-animate` are also not installed as well.
