### ISSUE TITLE
Combobox Cannot read properties of undefined (reading 'disabled') 

### ISSUE THREAD

**Issue by Fafnur** [qwikifiers/qwik-ui#699]
If you input any value and press enter, the component will throw an error.

You can see this simply by opening the documentation site:
https://qwikui.com/docs/headless/combobox/

### Example

<img width="1291" alt="Screenshot 2024-04-10 at 8 46 03 AM" src="https://github.com/qwikifiers/qwik-ui/assets/3624224/bbf5babb-9f45-4344-96b5-32b7e5b8a27d">

### Problem

Problem in onKeydownBehavior$:

<img width="663" alt="Screenshot 2024-04-10 at 8 48 22 AM" src="https://github.com/qwikifiers/qwik-ui/assets/3624224/2a3c4943-54da-4082-ac4a-bdb17f4c96c7">

**Comment by thejackshelton** [comment]
What browser? I don't get this error on chrome.

**Comment by Fafnur** [comment]
@thejackshelton Google Chrome Version 123.0.6312.124 (Official Build) (arm64) on macbook m1 max.

**Comment by thejackshelton** [comment]
Ah I see it now, thanks for making the issue 🙏

**Comment by thejackshelton** [comment]
fixed in 0.5
