### ISSUE TITLE
popover moves while scrolling?

### ISSUE THREAD

**Issue by osdiab** [qwikifiers/qwik-ui#710]
https://www.loom.com/share/6e0ffcb833d14f148650968ac8ec75c0

To me, it's table stakes for a library offering a popover to not look broken when you do common behaviors like scrolling; I expected the kind of robust behavior like what `floating-ui` or mature platforms like Radix (which also depends on `floating-ui`) provide.

Perhaps my understanding of the point of this library is incorrect, but is it supposed to be a native replacement for something like those libraries/is there any interest for this library to potentially depend on more robust (and platform-agnostic) libraries like that? Thanks!

**Comment by osdiab** [comment]
OK, I actually looked at the source and see that it is using `floating-ui`. I wonder if the website is just busted somehow that it isn't behaving as expected?

**Comment by osdiab** [comment]
Oh, is it that it doesn't use `floating` by default? OK, I think I get it now, I think just this page does a poor job of making the library seem robust then.

**Comment by thejackshelton** [comment]
While I agree that this is unintuitive when looking at a popover like Radix, this is actually feature parity with the native **popover api**. This is the correct behavior. Floating examples are further below. 

It looks like we need to improve the clarity surrounding this for sure though. PR's welcome.

I have been working on the popover / tests today.

**Comment by thejackshelton** [comment]
I have made a PR to explain that better. Will merge shortly.

**Comment by thejackshelton** [comment]
Merged. Closing
