### ISSUE TITLE
Tooltip props are inconsistent with those of Popover

### ISSUE THREAD

**Issue by osdiab** [qwikifiers/qwik-ui#713]
It uses different wordings, like `offset` instead of `gutter`, as well as lacking the more specific types that the Popover has for things like placements. Would make more sense if the popover and tooltips just shared from the same floating props as they're doing the same thing.

**Comment by thejackshelton** [comment]
Yep, that's the plan. The tooltip has been in there since the beginning of the project by another contributor. If someone does not get to it, then I will eventually. For now I would use the popover tooltip example.

**Comment by thejackshelton** [comment]
Closing as the tooltip was deprecated. Let's make an issue for the new one.
