### ISSUE TITLE
Tooltip can only have string contents

### ISSUE THREAD

**Issue by osdiab** [qwikifiers/qwik-ui#714]
Not sure if there's an a11y reason for this, but mature libraries like Radix UI let you put whatever content you want into tooltip contents. Would make more sense if it were a slot or something that allows for that flexibility.

**Comment by thejackshelton** [comment]
@osdiab I would say the tooltip is in a pre-alpha state even. You'd have more luck taking the tooltip example in the popover right now.

**Comment by thejackshelton-kunaico** [comment]
could you close this issue and make a new one as a feature request for a revamped tooltip? there might be one already

**Comment by thejackshelton** [comment]
could you close this issue and make a new one as a feature request for a revamped tooltip? there might be one already
