### ISSUE TITLE
Qwik UI Styled code examples wrong imports

### ISSUE THREAD

**Issue by shairez** [qwikifiers/qwik-ui#726]
The import from `@qwik-ui/styled` are misleading users - 

![image](https://github.com/qwikifiers/qwik-ui/assets/1430726/281fd5bc-bc6a-4012-bd23-7e1c93057a1d)

Maybe we can replace them with `~/components/ui` or something like that (or just remove the imports?

WDYT @maiieul ?

**Comment by maiieul** [comment]
Yes I agree! I'm working on a PR today :)

**Comment by thejackshelton** [comment]
@maiieul if you could just let me handle that. I already touch this since I'm switching to dot notation

**Comment by maiieul** [comment]
@thejackshelton we probably should pair on it :)
