### ISSUE TITLE
implement the full tooltip headless component with floating-ui + Daisy Impl

### ISSUE THREAD

**Issue by shairez** [qwikifiers/qwik-ui#74]

**Comment by nnelgxorz** [comment]
Todos:

- [ ] Auto positioning
- [ ] Fix initial un-positioned flicker
- [ ] Daisy theming
- [ ] Add tests / storybook

**Comment by nnelgxorz** [comment]
I'm taking the first three. @shairez can have fun with fixing the tests.

**Comment by tleperou** [comment]
Looks like tooltip is now implemented;

Could this issue be closed? - @shairez @nnelgxorz ?

**Comment by gioboa** [comment]
Yep we have it.
<img width="423" alt="Screenshot 2023-04-03 at 20 35 42" src="https://user-images.githubusercontent.com/35845425/229597113-8055fee8-2fda-407a-b1bd-7f9a44c41a78.png">
