### ISSUE TITLE
contributing: `pnpm i` with pnpm v9 after updating deps conflicts with nx

### ISSUE THREAD

**Issue by maiieul** [qwikifiers/qwik-ui#744]
If you `pnpm i` with pnpm v9 and above after updating a dependency, you'll get the following error:

    TypeError: Cannot read properties of undefined (reading 'CYAN600')
      25 |
      26 |   options.style = options.style ?? ThemeStyle.SIMPLE;
    > 27 |   options.primaryColor = options.primaryColor ?? ThemePrimaryColor.CYAN600;
         |                                                                    ^
      28 |
      29 |   options.borderRadius = options.borderRadius ?? ThemeBorderRadius['BORDER-RADIUS-0'];
      30 |

      at setupTailwindGenerator (src/generators/setup-tailwind/setup-tailwind-generator.ts:27:68)
      at Object.<anonymous> (src/generators/setup-tailwind/setup-tailwind-generator.spec.ts:83:33)
      
It has been reported already https://github.com/nrwl/nx/issues/22481, but needs an MRE.

**Comment by shairez** [comment]
Solved by #872
