### ISSUE TITLE
Styled input is broken `Cannot set properties of undefined (setting 'value')`

### ISSUE THREAD

**Issue by ziimakc** [qwikifiers/qwik-ui#764]
For component
```
<Input type="email" />
```

On input typing following error is shown:

```
Cannot set properties of undefined (setting 'value')
```

Reason is this line:
```
bind:value={valueSig}
```

**Comment by thejackshelton** [comment]
Hey @ziimakc! There appears to be an issue with core and this prop with the optimizer. As a result, I've added a workaround for now that should get this up and functional after the next release 👍

**Comment by thejackshelton** [comment]
You can also feel free to try the changes now with the pkg pr new on the issue mentioned above.
