### ISSUE TITLE
Headless UI?

### ISSUE THREAD

**Issue by japomani** [qwikifiers/qwik-ui#79]
Accessibility is super important in my environment, and DaisyUI has real issues when it comes to accessibility. 

Have you considered using a UI set like Headless UI that puts accessibility first?

**Comment by shairez** [comment]
Yes, this week we'll publish our initial headless pacakge, but that's the idea - to have a headless package and to have "themes", so daisy will only be the theme but all the controls and logic will be handled by the `@qwik-ui/headless`

**Comment by japomani** [comment]
Thanks for clarifying, good luck!

**Comment by shairez** [comment]
sure, thanks!
