### ISSUE TITLE
Docs: update Astro Logo in Installation Guide

### ISSUE THREAD

**Issue by at-the-vr** [qwikifiers/qwik-ui#807]
The [Meta Framework Guide](https://qwikui.com/docs/headless/install/#meta-framework-guides) section is using an old logo for Astro and can be updated from [Astro press](https://astro.build/press/#assets)

**Comment by maiieul** [comment]
Hey @at-the-vr! Thanks for reporting that! Up for a PR? 👀

**Comment by at-the-vr** [comment]
For sure 😄
