### ISSUE TITLE
[✨] headless toggle

### ISSUE THREAD

**Issue by maiieul** [qwikifiers/qwik-ui#811]
Something similar to Radix would be cool https://www.radix-ui.com/primitives/docs/components/toggle

**Comment by JerryWu1234** [comment]
Do  you mean that qwikUi wants to has a new component `toggle`?

**Comment by maiieul** [comment]
Yes would be cool to have a Toggle component similar to Radix.

**Comment by ArkadiK94** [comment]
@maiieul Hi, I am new here, I covered the Qwik School mini course and read the readme file. I would like to handle this issue. Could you assign me?

**Comment by maiieul** [comment]
@ArkadiK94 Steff on Discord has also started working on it. Can you join the conversation there? 😊
