### ISSUE TITLE
[🐞] Qwik UI Combobox styled component is not in sync with headless ui latest changes.

### ISSUE THREAD

**Issue by harshmangalam** [qwikifiers/qwik-ui#903]
### Which package is affected?

Styled Kit

### Describe the bug

The styled component for Combobox is still using deprecated ` Option` and missing `Item`,  `ItemLabel` and `ItemIndicator` Components.

### Reproduction

https://qwikui.com/docs/styled/combobox/

### Steps to reproduce

```sh
pnpm qwik-ui add combobox
```

### System Info

```shell
NA
```

**Comment by cwoolum** [comment]
Completed by @thejackshelton  in https://github.com/qwikifiers/qwik-ui/pull/838
