### ISSUE TITLE
[🐞] MakeItYours's CopyCSSConfig shiki code flickers when clicking on "Copy CSS" button

### ISSUE THREAD

**Issue by maiieul** [qwikifiers/qwik-ui#907]
Perhaps using a computed sig would solve it 🤔

**Comment by thejackshelton** [comment]
> Perhaps using a computed sig would solve it 🤔

How to reproduce?

**Comment by maiieul** [comment]
Wait whaat. It doesn't happen on qwik-ui.com 😅. I thought it did! Maybe this was fixed by your recent shiki PR!!! Awesome either way. So closing 🙈
