### ISSUE TITLE
[🐞]

### ISSUE THREAD

**Issue by barel-mishal** [qwikifiers/qwik-ui#912]
### Which package is affected?

Headless Kit

#### Description
I’m encountering an issue with the Qwik modal component in my application. I have a modal that works correctly in one part of my app but misbehaves in others. When I use `bind:show={admin.modalShow}` to control the modal's visibility, the backdrop covers the entire screen unintentionally, and buttons inside the modal either flicker or do not appear.

#### Code Example
Here's a simplified version of my component setup:

```jsx
<Modal.Root closeOnBackdropClick={true} bind:show={admin.modalShow}>
  <Modal.Trigger class="btn" onClick$={async () => {
    await admin.store.update({ action: "set-form", record: props.id as "Ingredient" })
  }}>
    <PhPencil class="h-5 fill-blue-500" />
  </Modal.Trigger>
  <Modal.Panel class="bg-white dark:bg-gray-950 text-gray-50 p-4 data-[state='open']:h-4/5
    data-[state='open']:rounded-lg data-[state='open']:shadow-lg">
    <Modal.Close class="btn">
      <div>Close</div>
    </Modal.Close>
    <h2 class="text-2xl font-semibold">Create New Food Item</h2>
    <Resource value={admin.forms}
      onResolved={(v) => {
        return <CreateForm data={v} key={`form-${props.id}`} recordId={props.id} submit={"update"} />
      }}
      onPending={() => <div>Loading...</div>}
    />
  </Modal.Panel>
</Modal.Root>
```

#### What I've Tried
1. Verified that `admin.modalShow` is a `Signal<boolean>` and logs changes to console.
2. Checked CSS styles to ensure no unintended styles cause the backdrop to cover the screen.
3. Inspected DOM elements to confirm correct rendering.
4. Used the console log to trace the state changes of `admin.modalShow`.

#### Observations
- When `bind:show={admin.modalShow}` is not used, the modal displays and functions correctly.
- The issue arises only when the modal is controlled using the `bind:show` signal.
- The DOM structure looks correct, but styles seem off when `bind:show` is in effect.

#### CSS Example
Here’s the CSS applied to the modal:

### Reproduction

Hope to do something soon

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 279.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.2 - ~/.nvm/versions/node/v21.6.2/bin/node
    npm: 10.8.2 - ~/projects/publish_notes/frontend/node_modules/.bin/npm
    pnpm: 9.1.0 - ~/Library/pnpm/pnpm
    bun: 1.1.21 - ~/.bun/bin/bun
    Watchman: 2024.04.01.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 127.0.6533.89
    Safari: 17.5
  npmPackages:
    @builder.io/qwik: ^1.7.3 => 1.7.3 
    @builder.io/qwik-auth: ^0.2.2 => 0.2.2 
    @builder.io/qwik-city: ^1.7.3 => 1.7.3 
    @builder.io/qwik-labs: github:BuilderIo/qwik-labs-build#main => 0.0.1 
    @qwik-ui/headless: ^0.4.4 => 0.4.4 
    @qwik-ui/styled: ^0.1.0 => 0.1.0 
    @qwik-ui/utils: ^0.2.1 => 0.2.1 
    typescript: ^5.5.4 => 5.5.4 
    undici: ^6.19.5 => 6.19.5 
    vite: ^5.3.5 => 5.3.5
```

**Comment by maiieul** [comment]
Solved on Discord.
