### ISSUE TITLE
[🐞] When using showcase with Qwik UI Tabs preview fails in Qwik 1.8

### ISSUE THREAD

**Issue by thejackshelton-kunaico** [qwikifiers/qwik-ui#923]
### Which package is affected?

Documentation Website

### Describe the bug

```
          {MetaGlobComponentSig.value && <MetaGlobComponentSig.value />}
```

In 1.8 when this is inside of a Tab Panel, then it will error in preview with the following:
```tsx
Cannot resolve symbol s_3HTehHcTjWI in {
  G07uFGFY56E: [ 's_G07uFGFY56E', 'q-5yi8seKT.js' ],
  ngAED40tnU4: [ 's_ngAED40tnU4', 'q-CV_3YgAZ.js' ],
  or3ZWgi00hc: [ 's_or3ZWgi00hc', 'q-Cdb4TUDQ.js' ],
  pO2IxuIv0ec: [ 's_pO2IxuIv0ec', 'q-CtLGhHYj.js' ],
  sr5f8jiJpXw: [ 's_sr5f8jiJpXw', 'q-C3QgeTBr.js' ],
  '02wMImzEAbk': [ 's_02wMImzEAbk', 'q-roBc8y6w.js' ],
  ```
  
  I believe something in 1.8 has broken the q-manifest, causing this bug. (not confirmed)

### Reproduction

qwikui.com

### Steps to reproduce

1. Upgrade to 1.8
2. run preview
3. navigate to a route with the showcase component

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M3
    Memory: 358.53 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - /usr/local/bin/node
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 9.5.0 - /usr/local/bin/pnpm
    bun: 1.1.7 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 125.1.66.118
    Chrome: 127.0.6533.100
    Safari: 17.5
```

**Comment by wmertens** [comment]
Can you find `3HTehHcTjWI` anywhere?

**Comment by thejackshelton** [comment]
> Can you find `3HTehHcTjWI` anywhere?

I checked via the project wide search, also looking through the q-manifest and some of the chunks, wasn't able to find it.

**Comment by maiieul** [comment]
Closing as I have a repro. Will make it in qwik repo if not solved in the coming weeks.
