### ISSUE TITLE
Mock up and implement design of documentation page

### ISSUE THREAD

**Issue by shiroinegai** [qwikifiers/qwik-ui#93]

**Comment by gioboa** [comment]
Here is the mockup we've done
<img width="1072" alt="Screenshot 2023-02-01 at 22 13 53" src="https://user-images.githubusercontent.com/35845425/216270081-3c9b0bb6-761d-4db0-9405-7744bb51a74d.png">

**Comment by gioboa** [comment]
First implementation with this PR #143
